* What is an interpreter

An interpreter runs your code as machine code directly. This sits in contrast to a
compiler which first ~compiles~ your code (shocking). The difference being that
a compiler is a meta program which has access to all your code prior to running
anything. This allows compilers to optimize your code and to do some other fun
things that are often too heavy weight for interpreted languages.

Interpreted languages on the other hand are much more portable -- you don't have
to care about different compiler behaviors, and such.

An interpreter has two steps:
 1. Parsing: This step reads the code, makes sure that it follows the syntax of
    our language, and creates some representation of our code -- most often a
    syntax tree.
 2. Evaluating/execution: This function actually executes the code. It takes the
    abstract syntax tree and enforces the semantics of the code. That is the
    code is doing what it is meant to do, an if statement is checking the
    predicate and returning either the consequent or the alternate.
